// Converts every PNG/JPG the site references under public/img to a resized
// WebP, rewrites the references in src/, and records each image's real
// size in src/data/imageSizes.ts (so lazy-loaded images can reserve their
// height before they load - pinned/scrubbed sections measure the layout
// early and would otherwise be thrown off).
//
// Originals are moved to originals/ (outside public/, so they stay out of
// the export) rather than deleted. Images that aren't referenced anywhere
// are left untouched. Safe to re-run after adding new images.
//
//   node scripts/convert-images.mjs

import { readdir, readFile, writeFile, mkdir, rename, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const MAX_WIDTH = 2000;
const QUALITY = 80;
// Read from disk by the Open Graph image route - ImageResponse can't
// decode WebP, so the original stays in public/ next to its WebP copy.
const KEEP_ORIGINAL = new Set(["/img/m2.png"]);

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p)));
    else if (/\.(tsx?|css)$/.test(entry.name)) out.push(p);
  }
  return out;
}

const srcFiles = await walk(join(ROOT, "src"));
const sources = new Map(await Promise.all(srcFiles.map(async (f) => [f, await readFile(f, "utf8")])));

const refRe = /\/img\/[^"'`()\s]+\.(?:png|jpe?g)/gi;
const refs = new Set();
for (const text of sources.values()) for (const m of text.matchAll(refRe)) refs.add(m[0]);

const sizesPath = join(ROOT, "src/data/imageSizes.ts");
const sizes = {};
try {
  const existing = await readFile(sizesPath, "utf8");
  for (const m of existing.matchAll(/"([^"]+)": \[(\d+), (\d+)\]/g)) sizes[m[1]] = [+m[2], +m[3]];
} catch {}

const renames = new Map();
for (const ref of [...refs].sort()) {
  const input = join(ROOT, "public", ref);
  try {
    await stat(input);
  } catch {
    console.warn(`missing, skipped: ${ref}`);
    continue;
  }
  const webpRef = ref.replace(/\.(png|jpe?g)$/i, ".webp");
  const { data, info } = await sharp(input)
    .rotate() // apply EXIF orientation before it's stripped
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toBuffer({ resolveWithObject: true });
  await writeFile(join(ROOT, "public", webpRef), data);
  sizes[webpRef] = [info.width, info.height];
  renames.set(ref, webpRef);

  if (!KEEP_ORIGINAL.has(ref)) {
    const dest = join(ROOT, "originals", ref);
    await mkdir(dirname(dest), { recursive: true });
    await rename(input, dest);
  }
  const before = (await stat(KEEP_ORIGINAL.has(ref) ? input : join(ROOT, "originals", ref))).size;
  console.log(`${ref} -> ${webpRef}  ${(before / 1e6).toFixed(1)}MB -> ${(data.length / 1e6).toFixed(2)}MB`);
}

for (const [file, text] of sources) {
  let next = text;
  for (const [from, to] of renames) {
    // Leave the OG route reading its PNG from disk.
    if (KEEP_ORIGINAL.has(from) && file.includes("opengraph-image")) continue;
    next = next.split(from).join(to);
  }
  if (next !== text) await writeFile(file, next);
}

const lines = Object.keys(sizes)
  .sort()
  .map((k) => `  "${k}": [${sizes[k][0]}, ${sizes[k][1]}],`);
await writeFile(
  sizesPath,
  `// Generated by scripts/convert-images.mjs - real width/height of each
// image, so <img> tags can reserve their space before loading.
export const imageSizes: Record<string, [number, number]> = {
${lines.join("\n")}
};

// width/height attributes for an <img>, when the size is known.
export function imgSize(src: string): { width?: number; height?: number } {
  const size = imageSizes[src];
  return size ? { width: size[0], height: size[1] } : {};
}
`
);
